import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { getServerSession, Session } from "next-auth";
import { authConfig } from "@/lib/auth";
import { useEffect, useState } from "react";
import { SessionContext } from "next-auth/react";

import { NextAuthProvider } from "./Providers";
import Navbar from "@/app/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <Navbar />
          <div className="childrencontainer">
            {children}
          </div>
        </NextAuthProvider>



      </body>
    </html>
  );
}
